replicaCount: 1

appInClusterNamespace: default

targetCluster:
  labelSelector:
    matchLabels:
      #vendor: "ICP"
      #region: "US"
      #environment: Dev
      #datacenter: "toronto"
      #owner: "marketing"
  resourceSelector:
    type: cpu
  compliances: ""